<?php


namespace App\Facade;


use Illuminate\Support\Facades\Facade;

class CaseRepository extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'CaseRepository'; // TODO: Change the autogenerated stub
    }
}
